controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    fishbot_joint_state_broadcaster: #fishbot_joint_state_broadcaster就是控制器生成的对应节点的节点名
      type: joint_state_broadcaster/JointStateBroadcaster
      use_sim_time: true

    fishbot_effort_controller: #fishbot_effort_controller就是控制器生成的对应节点的节点名
      type: effort_controllers/JointGroupEffortController



fishbot_effort_controller:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
